version: '3.7'
services:
  fwlib:
    image: strangesast/fwlib
    build:
      context: external/fwlib
  driver:
    depends_on:
      - fwlib
    image: strangesast/fanuc-minimal-example
    network_mode: host
    build:
      context: .
    command: fanuc_example 127.0.0.1 8193
